#!/bin/sh
# -------------------------------------------------------------------------------
# Post-remove script for cloudflare-log-collector
# -------------------------------------------------------------------------------
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/cloudflare-log-collector
fi
